# Generated by Django 5.1.5 on 2026-07-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirplanesData',
            fields=[
                # ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_code', models.CharField(max_length=3, primary_key=True)),
                ('model', models.JSONField(blank=True, null=True)),
                ('range', models.PositiveSmallIntegerField(default=0)),
                ('speed', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'airplanes_data',
                'managed': False,
            },
        ),
    ]
