# Generated by Django 5.1.5 on 2026-07-17 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportsData',
            fields=[
                ('airport_code', models.CharField(db_comment='Airport code, IATA', max_length=3, primary_key=True, serialize=False)),
                ('airport_name', models.JSONField(db_comment='Airport name')),
                ('city', models.JSONField(db_comment='City')),
                ('country', models.JSONField(db_comment='Country')),
                ('coordinates', models.TextField(db_comment='Airport coordinates (longitude and latitude)')),
                ('timezone', models.TextField(db_comment='Airport time zone')),
            ],
            options={
                'db_table': 'airports_data',
                'db_table_comment': 'Airports (internal multilingual data)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('book_ref', models.CharField(db_comment='Booking number', max_length=6, primary_key=True, serialize=False)),
                ('book_date', models.DateTimeField(db_comment='Booking date')),
                ('total_amount', models.DecimalField(db_comment='Total booking amount', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'bookings',
                'db_table_comment': 'Bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.AutoField(db_comment='Flight ID', primary_key=True, serialize=False)),
                ('route_no', models.TextField(db_comment='Route number')),
                ('status', models.TextField(db_comment='Flight status')),
                ('scheduled_departure', models.DateTimeField(db_comment='Scheduled departure time')),
                ('scheduled_arrival', models.DateTimeField(db_comment='Scheduled arrival time')),
                ('actual_departure', models.DateTimeField(blank=True, db_comment='Actual departure time', null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, db_comment='Actual arrival time', null=True)),
            ],
            options={
                'db_table': 'flights',
                'db_table_comment': 'Flights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.TextField(db_comment='Route number')),
                ('validity', models.TextField(db_comment='Period of validity')),
                ('days_of_week', models.TextField(db_comment='Days of week array')),
                ('scheduled_time', models.TimeField(db_comment='Scheduled local time of departure')),
                ('duration', models.DurationField(db_comment='Estimated duration')),
            ],
            options={
                'db_table': 'routes',
                'db_table_comment': 'Routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('airplane_code', models.OneToOneField(db_column='airplane_code', db_comment='Airplane code, IATA', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='passengers.airplanesdata')),
                ('seat_no', models.TextField(db_comment='Seat number')),
                ('fare_conditions', models.TextField(db_comment='Travel class')),
            ],
            options={
                'db_table': 'seats',
                'db_table_comment': 'Seats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_no', models.TextField(db_comment='Ticket number', primary_key=True, serialize=False)),
                ('passenger_id', models.TextField(db_comment='Passenger ID')),
                ('passenger_name', models.TextField(db_comment='Passenger name')),
                ('outbound', models.BooleanField(db_comment='Outbound flight?')),
            ],
            options={
                'db_table': 'tickets',
                'db_table_comment': 'Tickets',
                'managed': False,
            },
        ),
        migrations.AlterModelTableComment(
            name='airplanesdata',
            table_comment='Airplanes (internal multilingual data)',
        ),
        migrations.CreateModel(
            name='Segments',
            fields=[
                ('ticket_no', models.OneToOneField(db_column='ticket_no', db_comment='Ticket number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='passengers.tickets')),
                ('fare_conditions', models.TextField(db_comment='Travel class')),
                ('price', models.DecimalField(db_comment='Travel price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'segments',
                'db_table_comment': 'Flight segment (leg)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardingPasses',
            fields=[
                ('ticket_no', models.OneToOneField(db_column='ticket_no', db_comment='Ticket number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='passengers.segments')),
                ('flight_id', models.IntegerField(db_comment='Flight ID')),
                ('seat_no', models.TextField(db_comment='Seat number')),
                ('boarding_no', models.IntegerField(blank=True, db_comment='Boarding pass number', null=True)),
                ('boarding_time', models.DateTimeField(blank=True, db_comment='Boarding time', null=True)),
            ],
            options={
                'db_table': 'boarding_passes',
                'db_table_comment': 'Boarding passes',
                'managed': False,
            },
        ),
    ]
