# Generated by Django 5.1.5 on 2026-07-17 06:00

from django.db import migrations

CREATE_FLIGHT_MILEAGE = """
CREATE MATERIALIZED VIEW IF NOT EXISTS passenger_flight_mileage AS
SELECT
    s.ticket_no,
    s.flight_id,
    t.passenger_id,
    t.passenger_name,
    (f.actual_departure AT TIME ZONE 'UTC')::date AS flight_date,
    round(
        (6371 * acos(least(1.0, greatest(-1.0,
            sin(radians((dep.coordinates)[1])) * sin(radians((arr.coordinates)[1]))
          + cos(radians((dep.coordinates)[1])) * cos(radians((arr.coordinates)[1]))
          * cos(radians((arr.coordinates)[0]) - radians((dep.coordinates)[0]))
        ))))::numeric,
        2
    ) AS distance_km,
    s.price
FROM segments s
JOIN tickets t ON t.ticket_no = s.ticket_no
JOIN flights f ON f.flight_id = s.flight_id
JOIN (
    -- route_no -> aeroportlar birga-bir mos (validity bo'yicha farq qilmaydi)
    SELECT DISTINCT ON (route_no) route_no, departure_airport, arrival_airport
    FROM routes
) r ON r.route_no = f.route_no
JOIN airports_data dep ON dep.airport_code = r.departure_airport
JOIN airports_data arr ON arr.airport_code = r.arrival_airport
WHERE f.status = 'Arrived'
  AND f.actual_departure IS NOT NULL
WITH DATA;
"""

CREATE_MILEAGE_SUMMARY = """
CREATE MATERIALIZED VIEW IF NOT EXISTS passenger_mileage_summary AS
SELECT
    passenger_id,
    max(passenger_name) AS passenger_name,
    count(*)::int        AS valid_flights,
    sum(distance_km)     AS total_distance_km,
    sum(price)           AS total_spent,
    round(avg(price), 2) AS avg_segment_price,
    max(price)           AS max_segment_price,
    min(price)           AS min_segment_price,
    CASE
        WHEN sum(distance_km) >= 50000 THEN 'Platinum'
        WHEN sum(distance_km) >= 15000 THEN 'Gold'
        WHEN sum(distance_km) >= 5000  THEN 'Silver'
        ELSE 'Bronze'
    END AS tier
FROM passenger_flight_mileage
GROUP BY passenger_id
WITH DATA;
"""

CREATE_INDEXES = """
CREATE UNIQUE INDEX IF NOT EXISTS pfm_ticket_flight_uidx
    ON passenger_flight_mileage (ticket_no, flight_id);
CREATE INDEX IF NOT EXISTS pfm_flight_date_idx
    ON passenger_flight_mileage (flight_date);

CREATE UNIQUE INDEX IF NOT EXISTS pms_passenger_uidx
    ON passenger_mileage_summary (passenger_id);
CREATE INDEX IF NOT EXISTS pms_distance_idx
    ON passenger_mileage_summary (total_distance_km DESC);
CREATE INDEX IF NOT EXISTS pms_spent_idx
    ON passenger_mileage_summary (total_spent DESC);
CREATE INDEX IF NOT EXISTS pms_flights_idx
    ON passenger_mileage_summary (valid_flights DESC);
CREATE INDEX IF NOT EXISTS pms_tier_distance_idx
    ON passenger_mileage_summary (tier, total_distance_km DESC);
"""

DROP_ALL = """
DROP MATERIALIZED VIEW IF EXISTS passenger_mileage_summary;
DROP MATERIALIZED VIEW IF EXISTS passenger_flight_mileage;
"""


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('passengers', '0003_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.RunSQL(CREATE_FLIGHT_MILEAGE, reverse_sql=DROP_ALL),
        migrations.RunSQL(CREATE_MILEAGE_SUMMARY, reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(CREATE_INDEXES, reverse_sql=migrations.RunSQL.noop),
    ]
