# Generated by Django 5.1.5 on 2026-07-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0004_mileage_materialized_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerFlightMileage',
            fields=[
                ('ticket_no', models.TextField(primary_key=True, serialize=False)),
                ('flight_id', models.IntegerField()),
                ('passenger_id', models.TextField()),
                ('passenger_name', models.TextField()),
                ('flight_date', models.DateField(db_comment='Reys uchgan sana (actual_departure, UTC)')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'passenger_flight_mileage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerMileageSummary',
            fields=[
                ('passenger_id', models.TextField(primary_key=True, serialize=False)),
                ('passenger_name', models.TextField()),
                ('valid_flights', models.IntegerField()),
                ('total_distance_km', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=14)),
                ('avg_segment_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_segment_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_segment_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tier', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'passenger_mileage_summary',
                'managed': False,
            },
        ),
    ]
